import { Injectable } from '@angular/core';
import { IQuestion } from '../interfaces/IQuestion';

@Injectable({
  providedIn: 'root'
})
export class QuestionsService {

  private questions: IQuestion[] = [
    {
      id: 1,
      question: 'Which of the following is not a Development Environment?',
      options: ['Service Studio', 'Integration Studio', 'Service Center'],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! Service Center is a management and administration console for one environment (e.g. Development, Production).'
    },
    {
      id: 2,
      question: 'One of the following Tools allows you to manage the application\'s lifecycle across an infrastructure. Which one?',
      options: ['Service Center', 'LifeTime', 'Service Studio', 'Integration Studio'],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! Besides that, it also allows you to manage IT users and teams.'
    },
    {
      id: 3,
      question: 'During the 1-Click Publish, your application data model, code, and interface is compiled and generates .NET code, HTML, JavaScript and CSS. True or False?',
      options: ['True', 'False'],
      correctOption: 0,
      anwserExplanation:'That\'s Right! And the code that is generated is also optimized.'
    },
    {
      id: 4,
      question: 'In which Service Studio layer can Screens and Blocks be found?',
      options: ['Processes', 'Interface', 'Logic', 'Data'],
      correctOption: 1,
      anwserExplanation:'That\'s Right! You can also find Images and Themes in this layer'
    },
    {
      id: 5,
      question: 'In which Service Studio layer can Entities be found?',
      options: ['Interface', 'Processes', 'Logic', 'Data'],
      correctOption: 3,
      anwserExplanation:'That\'s Right! This is where you can find data-related elements, such as Entity diagrams and structures.'
    },
    {
      id: 6,
      question: 'Which of the following is not a type of module in OutSystems?',
      options: ['Mobile', 'Web', 'Business', 'Logic'],
      correctOption: 2,
      anwserExplanation:'That\'s Right! The other types are Web, Mobile, and Logic.'
    },
    {
      id: 7,
      question: 'Regarding Reactive Web Apps in OutSystems, which of the following options is false?',
      options: [
        'A Reactive Web App is a cross-device app', 
        'Data requests are executed synchronously.', 
        'The code generated by OutSystems results in a single-page application.', 
        'A developer builds the Reactive Web App in Service Studio.'
      ],
      correctOption: 1,
      anwserExplanation:'That\'s Right! Data is requested asynchronously, thus allowing a more fluid experience.'
    },
    {
      id: 8,
      question: 'Regarding Mobile (Phone or Tablet) Apps in OutSystems, which of the following options is false?',
      options: [
        'Mobile Apps can run natively on iOS and Android.',
        'Mobile Apps can be distributed as a PWA.',
        'Mobile Apps do not have offline capabilities.',
        'The programming model of Mobile Apps is similar to Reactive Web Apps.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! Actually, Mobile Apps have access to local storage and can be developed to work offline, online, or in both scenarios.'
    },
    {
      id: 9,
      question: 'What happens when a developer publishes a Module?',
      options: [
        'The OutSystems platform compiles it and generates the HTML, CSS, and JavaScript.',
        'The browser opens.',
        'Nothing.',
        'The code is uploaded but only compiled when a user accesses the application.'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! After that, the application can be tested on the browser.'
    },
    {
      id: 10,
      question: 'Which of the following options is false regarding Modules and applications?',
      options: [
        'An application is composed of a set of Modules.',
        'Modules can be of different types, such as Reactive Web App, Blank, or Extension.',
        'Elements can be exposed and reused, but only within the same application.',
        'A Module that reuses an element from another Module is called a Consumer.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! Only within the same application? That sounds a bit restrictive...'
    },
    {
      id: 11,
      question: 'Business concepts that need to be stored and accessed in our applications should be modeled as...',
      options: [
        'Entities.',
        'Entity diagrams.',
        'Entity relationships.',
        'Database tables.'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! Ideally, each business concept will be mapped into a single entity.'
    },
    {
      id: 12,
      question: 'Which of the following mappings between OutSystems and the Database is NOT correct?',
      options: [
        'Entities - Tables.',
        'Attributes - Column.',
        'Reference attribute - Primary Key.',
        'Index - Index.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! Ooops... Entity identifiers are the ones that are mapped into primary keys.'
    },
    {
      id: 13,
      question: 'Which of the following statements about Entities is false?',
      options: [
        'Entities have attributes.',
        'Entities do not require an identifier.',
        'Entities are only stored in memory.',
        'Entities can be created, updated, and deleted.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! Entities are persistent and are actually created in the database as tables.'
    },
    {
      id: 14,
      question: 'If an Entity Attribute named HouseNumber is created, what needs to be done about its Data Type?',
      options: [
        'It should be set to Integer.',
        'It should be set to Decimal.',
        'Nothing, it will automatically be set to Identifier.',
        'Nothing, it will automatically be set to Integer.'
      ],
      correctOption: 3,
      anwserExplanation: 'That\'s Right! The OutSystems Data Type Inference mechanism handles it.'
    },
    {
      id: 15,
      question: 'Which of the following is not an Entity Action of the Customer Entity?',
      options: [
        'CreateCustomer.',
        'RetrieveCustomer.',
        'UpdateCustomer.',
        'DeleteCustomer.'
      ],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! The Entity Action that allows retrieving data is the Get.'
    },    
    {
      id: 16,
      question: 'Which of the following is a characteristic of a Static Entity?',
      options: [
        'It can\'t be changed after the first publish.',
        'It contains a set of Records.',
        'It has two Entity Actions.',
        'It can\'t be extended with any new attributes.'
      ],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! As many as you want but they need to be defined during development.'
    },
    {
      id: 17,
      question: 'Regarding the Records of a Static Entity, which of the following options is false?',
      options: [
        'The values for all 4 default attributes must be defined.',
        'Records can only be added and removed during development.',
        'The record identifier is the identifier of Static Entity.',
        'The Identifier attribute is required for all Static Entities.'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! Attributes of static entities can be mandatory or not. A value is only required to be set if the attribute is mandatory.'
    },
    {
      id: 18,
      question: 'Static Entities are most similar to which other programming concept?',
      options: [
        'Linked lists.',
        'Enumeration.',
        'Hash Maps.',
        'Static variables.'
      ],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! This is the closest one.'
    },
    {
      id: 19,
      question: 'Regarding data relationships, which of the following options is correct?',
      options: [
        'An Entity must have an identifier to allow relationships.',
        'A reference attribute needs to be mandatory.',
        'An Entity can only have one reference attribute.',
        'The Entity identifier must be an integer.'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! The relationships are created by setting an attribute with data type Entity Identifier!'
    },
    {
      id: 20,
      question: 'Which of the following steps is necessary to create a 1-to-1 relationship between Entity A and Entity B?',
      options: [
        'Set the data type of the identifier attribute of Entity B to Entity A Identifier.',
        'Add a new Entity C, with two reference attributes of type Entity A Identifier and Entity B Identifier.',
        'Add a new reference attribute of type Entity B Identifier to Entity A.',
        'Add a new Entity C, with the identifier attribute being a composition of types Entity A Identifier and Entity B Identifier.'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! Entity B will be an extension of Entity A, so they will share the same identifier.'
    },
    {
      id: 21,
      question: 'Which of the following steps is necessary to create a 1-to-many relationship between a Master Entity A and a Detail Entity B?',
      options: [
        'Set the data type of the identifier attribute of Entity B to Entity A Identifier.',
        'Add a new Entity C, with two reference attributes of type Entity A Identifier and Entity B Identifier.',
        'Entity A must have a reference attribute of type Entity B Identifier.',
        'Entity B must have a reference attribute of type Entity A Identifier.'
      ],
      correctOption: 3,
      anwserExplanation: 'That\'s Right! The Detail Entity has to reference the Master Entity.'
    },
    {
      id: 22,
      question: 'Which of the following steps is necessary to create a many-to-many relationship between Entity A and Entity B?',
      options: [
        'Set the data type of the identifier attribute of Entity B to Entity A Identifier.',
        'Add a new reference attribute of type Entity B Identifier to Entity A.',
        'Add a new Entity C, with two reference attributes of type Entity A Identifier and Entity B Identifier.',
        'Add a new reference attribute of type Entity B Identifier to Entity A and a new reference attribute of type Entity A Identifier to Entity B.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! Entity C will be the junction Entity that helps supporting the many-to-many relationship.'
    },
    {
      id: 23,
      question: 'Regarding Indexes, which of the following options is correct?',
      options: [
        'Custom indexes cannot be added to an Entity.',
        'Indexes speed up data retrieval without any kind of impact.',
        'Unique indexes help prevent data duplication.',
        'Indexes over referenced attributes cannot be deleted.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! When a unique index is defined across a set of attributes, the data stored on those attributes will be unique.'
    },
    {
      id: 24,
      question: 'Regarding the Delete Rule property, which of the following options does not guarantee referential integrity?',
      options: [
        'Protect',
        'Delete',
        'Ignore'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! This option does not ensure referential integrity in the relationship and should be used with caution.'
    },
    {
      id: 25,
      question: 'Screens are composed of several elements called Widgets.',
      options: [
        'True',
        'False'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! Each one of the elements (e.g. Link, Image) inside a screen is called Widget.'
    },
    {
      id: 26,
      question: 'What type of variables can be created inside a Screen?',
      options: [
        'Local Variables only.',
        'Input Parameters only.',
        'Input Parameters and Local Variables.',
        'Input Parameters, Output Parameters, and Local Variables.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! Screens do not have Output Parameters.'
    },
    {
      id: 27,
      question: 'Which of the following options is false?',
      options: [
        'Input Parameters allow passing data between Screens when navigating between them.',
        'Local Variables from a Screen may be directly accessed from another Screen.',
        'Local Variables allow temporarily storing relevant information inside a Screen.',
        'When the value of a Local Variable changes the user interface reacts immediately.'
      ],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! The scope of Input Parameters and Local Variables is limited to the Screen where they are defined.'
    },
    {
      id: 28,
      question: 'The Expression widget...',
      options: [
        '... displays only static text.',
        '... displays text calculated at runtime.',
        '... displays only the result of mathematical expressions.'
      ],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! Expression widget displays "calculated" values, evaluated at runtime that may depend on, for example, variables.'
    },
    {
      id: 29,
      question: 'Which of the following behaviors is true for Links and Buttons?',
      options: [
        'Links can only navigate to Screens.',
        'Buttons can only have a Screen Action as an On Click Destination.',
        'Links and Buttons can either Navigate to screens or trigger Screen Actions.',
        'Only Links can navigate to external URLs.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! Users can interact with the application by clicking or tapping Links and Buttons. This triggers an action, submits data or navigates to another screen.'
    },
    {
      id: 30,
      question: 'Regarding the If Widget, which of the following options is false?',
      options: [
        'Functions can be used inside the Condition of an If.',
        'More branches can be added to an If Widget.',
        'Only one of the branches is shown at runtime.',
        'Multiple widgets may be added inside each branch.'
      ],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! Every If widget only has two branches: True and False.'
    },
    {
      id: 31,
      question: 'Regarding the Container widget, which of the following options is false?',
      options: [
        'Containers allow grouping several widgets.',
        'By default, containers can span from 1 column up to 12 columns.',
        'Containers can be placed inside other containers.',
        'All containers must have at least one widget inside.'
      ],
      correctOption: 3,
      anwserExplanation: 'That\'s Right! They can actually be empty.'
    },
    {
      id: 32,
      question: 'In an Aggregate, the Sources section is used for...',
      options: [
        'Defining values for testing the Aggregate\'s output records.',
        'Defining the Entities we want to retrieve records from.',
        'Defining conditions to get specific subsets of records.',
        'Defining the order of the Aggregate\'s output records.'
      ],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! Yes! Aggregates support one or more source Entities and with relationships defined between them.'
    },
    {
      id: 33,
      question: 'Considering that we can add several filters to an Aggregate, which of the following options is false?',
      options: [
        'A record is included in the output if it matches at least one of the filters.',
        'Filters are concatenated with the AND operator.',
        'All filters are translated to SQL and included in the WHERE clause.',
        'Logical operators and some built-in functions can be used inside filters.'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! For a record to be included in the output result it must be true for all filters defined.'
    },
    {
      id: 34,
      question: 'Regarding Sorting in Aggregates, which of the following options is correct?',
      options: [
        'Aggregates only support one sorting criterion.',
        'If more than one sorting criterion is defined, all of them must have the same direction (ascending or descending).',
        'It is mandatory to set the direction for all sorting criteria (ascending or descending).',
        'It is only possible to set multiple sorting criteria if duplicate records exist in the entity.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! Sorting criteria direction has to be either Ascending or Descending.'
    },
    {
      id: 35,
      question: 'In an Aggregate, the purpose of the Test Values section is…',
      options: [
        'To define values for testing the preview of the Aggregate\'s output.',
        'To set the conditions to get specific records, not all the records.',
        'To define the order of its output records.',
        'To define the Entities we want to get records from.'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! The Test Values section is used for testing the Aggregate and preview the output records.'
    },
    {
      id: 36,
      question: 'Regarding Screen Aggregates, which of the following options is false?',
      options: [
        'Screen Aggregates run asynchronously and in parallel.',
        'Screen Aggregates only exist within the scope of the Screen where they were defined.',
        'Screen Aggregates can only be executed when explicitly called.',
        'Screen Aggregates can only fetch data from the database.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! By default, Screen Aggregates run automatically.'
    },
    {
      id: 37,
      question: 'How is the data fetched by an Aggregate bound to a Table or a List widget?',
      options: [
        'By setting the Source property of the widget to the output of the Aggregate.',
        'The binding is done automatically since the Aggregate is in the scope of the Screen.',
        'By adding an Expression inside the widget that refers to an attribute of the data fetched by the Aggregate.',
        'By creating a Screen Action that programmatically assigns the widget to the data fetched by the Aggregate.'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! The widgets have access to the output of the Screen Aggregates, so the binding can be easily defined through the Source property.'
    },
    {
      id: 38,
      question: 'Considering List Item and List Actions, which of the following options is false?',
      options: [
        'List Actions can only be used inside List Items.',
        'List Items can be used outside of Lists.',
        'When List Items have the full swiping option activated, the List Action is not necessary.',
        'The List Action triggers a Screen Action that will have the logic to be executed on swipe.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! Yes, it is, to determine what happens on swipe. It just uses the logic defined on the List Item.'
    },
    {
      id: 39,
      question: 'Using the Data Action output, we display a set of all Projects on the screen. Furthermore, we intend to show the details of the chosen project on the screen. How would you do that?',
      options: [
        'By setting the Source property of the Expression widget to the output of the Aggregate.',
        'By setting the Source property of the List widget to the output of the Aggregate.',
        'By setting the Value property of the List widget to the specific attribute of the Aggregate result.',
        'By setting the Value property of the Expression widget to the specific attribute of the Aggregate result.'
      ],
      correctOption: 3,
      anwserExplanation: 'That\'s Right! This will present the entire set of Projects on the screen, without displaying the individual project details. This will display the individual project details.'
    },
    {
      id: 40,
      question: 'How is the List Action defined to execute the necessary swipe action?',
      options: [
        'By setting the widget\'s Source property to the output of the Aggregate.',
        'By specifying the Client Action containing the required logic in the On-Click Destination property.',
        'By setting the On-Click Destination property to \'On.\'',
        'By defining the Client Action that contains the necessary logic for the Source property.'
      ],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! To ensure the execution of the desired swipe action, it is crucial to define the necessary Client Action within the On-click Decision property.'
    },
    {
      id: 41,
      question: 'How can you define the desired swipe actions to reveal actions/options when swiping left and full swipe action when swiping right?',
      options: [
        'Set both the Full Swipe Left and Full Swipe Right properties to "Yes".',
        'Set both the Full Swipe Left property and Full Swipe Right property to "No".',
        'Set the Full Swipe Left property to "No" and the Full Swipe Right property to "Yes."',
        'Set the Full Swipe Left property to "Yes" and the Full Swipe Right property to "No."'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! When the "Full Swipe Left" property is set to "No," swiping left will reveal actions and options, while swiping right will trigger the full swipe action.'
    },
    {
      id: 42,
      question: 'Which of the following behaviors does not apply to Forms?',
      options: [
        'A Form groups input widgets and allows displaying and editing data.',
        'A Form has a Source property that will hold the values submitted by the user.',
        'Besides input widgets, a Form can hold other widgets such as Links and Buttons.',
        'A Form is useful to validate data submitted by the user.'
      ],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! It\'s actually the Inputs within a Form that has a Variable property that will have the value in each Input.'
    },
    {
      id: 43,
      question: 'Considering the Dropdown and the Button Group, which of the following options is false?',
      options: [
        'A Button Group needs a Button Group Item to represent each option that the user will have available to choose from.',
        'The List property of the Dropdown defines the data that will appear as options to a user on a Screen.',
        'Each Button Group Item within a Button Group has a Variable property to save the option chosen by the user.',
        'The Variable property of the Dropdown will hold the value selected by the user. That value is defined in the Options Value property.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! This is indeed a false statement. The Variable property actually belongs to the Button Group, which is where the value of the chosen Item will be saved.'
    },
    {
      id: 44,
      question: 'The Checkbox or Switch Widgets are bound to a variable of which type?',
      options: [
        'Text',
        'Integer',
        'Boolean',
        'Date'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! That\'s it. True or false!'
    },
    {
      id: 45,
      question: 'Considering Inputs and Labels, which of the following options is correct?',
      options: [
        'Every input must have a Label associated with.',
        'An input widget can only be used for the Text data type.',
        'To access the value submitted in an Input widget, we can simply use InputName.Value.',
        'Labels associated with mandatory fields will display a visual cue on the Screen.'
      ],
      correctOption: 3,
      anwserExplanation: 'That\'s Right! That is actually a big advantage in having them!'
    },
    {
      id: 46,
      question: 'Can a Server action set as a Function have a multiple output parameter?',
      options: [
        'Yes',
        'No'
      ],
      correctOption: 1,
      anwserExplanation: 'That’s Right! Client and Server actions can be set as a function and is restricted to one output parameter and is Available in expressions.'
    },
    {
      id: 47,
      question: 'Which of the following options is correct?',
      options: [
        'Screen Actions can call other Screen Actions from a different screen.',
        'Client Actions can call Screen Actions.',
        'Server Actions can call Client Actions.',
        'Client Actions can call Server Actions.'
      ],
      correctOption: 3,
      anwserExplanation: 'That\'s Right! Similarly, Screen Actions can also call Server Actions.'
    },
    {
      id: 48,
      question: 'Client Actions and Server Actions can have the following variables:',
      options: [
        'Input and Output Parameters, but no Local variables.',
        'Input Parameters and Local Variables, but no Output Parameters.',
        'Input and Output Parameters, as well as Local Variables.',
        'Output Parameters and Local Variables, but no Input Parameters.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! They can have multiple input, output and local variables.'
    },
    {
      id: 49,
      question: 'The flow of an action can have...',
      options: [
        '... multiple Start and End nodes.',
        '... one or more Start nodes but only one End node.',
        '... only one Start node but multiple End nodes.',
        '... only one Start node and one End node.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! Action Flows can only have one Start node and can end in different End nodes.'
    },
    {
      id: 50,
      question: 'Regarding the If statement, which of the following options is false?',
      options: [
        'Both True and False branches are mandatory.',
        'Only one of the branches is executed, depending on the If condition\'s outcome.',
        'If statements can also be used to implement ad-hoc loops.',
        'More branches may be added if needed.'
      ],
      correctOption: 3,
      anwserExplanation: 'That\'s Right! Not to an If. Although in Switch statements that is possible.'
    },
    {
      id: 51,
      question: 'Regarding the Switch statement, which of the following options is false?',
      options: [
        'The first branch that the condition evaluates to True is executed.',
        'Every branch that evaluates to True is executed.',
        'If no branch evaluates to True, the Otherwise branch is executed.',
        'The Otherwise branch must exist.'
      ],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! Only one branch of the Switch is executed: the first one that evaluates to True. If none, then the Otherwise is executed.'
    },
    {
      id: 52,
      question: 'Is it necessary to have an Exception handler in our logic?',
      options: [
        'Yes, to prevent the exception from crashing the system.',
        'No, the Global exception handler will process the exception.'
      ],
      correctOption: 1,
      anwserExplanation: 'That’s Right! The global exception handler is defined under the Common UI Flow.'
    },
    {
      id: 53,
      question: 'Inside an Action flow...',
      options: [
        '... only one Exception Handler may exist.',
        '... it\'s mandatory to have at least one Exception Handler.',
        '... the Exception Handler flow can\'t intersect other flows.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! Each flow must be independent from the others.'
    },
    {
      id: 54,
      question: 'If we have multiple Exception Handlers in an Action flow and an Exception is raised...',
      options: [
        '... the execution is always moved to the Global Exception Handler.',
        '... the execution is moved to the Exception Handler that is most specific to the Exception.',
        '... the execution is moved to all Exception Handlers of the Action.',
        '... a Switch statement is needed to select which Exception Handler will continue the execution.'
      ],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! Different Exceptions are handled by different specific Handlers.'
    },
    {
      id: 55,
      question: 'What is the Screen behavior when a widget is not valid (Valid property set to False)?',
      options: [
        'The Screen displays the widget greyed out, and displays the validation error message on the input.',
        'The widget does not appear on the Screen and the validation message appears in its place.',
        'Displays the regular widget and displays the validation error message when we hover the mouse.',
        'Displays the regular widget, applies a specific styling (e.g. red border), and displays the validation error message.'
      ],
      correctOption: 3,
      anwserExplanation: 'That\'s Right! This way we can easily identify which inputs are not valid and why.'
    },
    {
      id: 56,
      question: 'Which of the following options is not a built-in validation for forms in OutSystems?',
      options: [
        'Mandatory Fields',
        'Maximum length of text fields',
        'Data types of input fields'
      ],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! Correct! Mandatory fields and data types are the validation performed automatically by the platform.'
    },
    {
      id: 57,
      question: 'Which of the following options is correct regarding the Valid property of the Form?',
      options: [
        'The Valid property of the Form should be checked after the last custom validation.',
        'The Valid property of the Form is automatically changed to False when all the input fields of the Form are not valid.',
        'The Valid property of the Form should be explicitly set to False (e.g. with an Assign) when an input field is not valid.',
        'When built-in validations are enabled, the Valid property of the Form is automatically checked before executing the client action logic.'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! This allows to branch the execution and avoid storing invalid data in the database.'
    },
    {
      id: 58,
      question: 'What is an Aggregate?',
      options: [
        'Integrated service to get data from database',
        'A SQL query constructor',
        'A Visual element to allows you to define a query to fetch data from entities',
        'An action server to retry data'
      ],
      correctOption: 2,
      anwserExplanation: 'That’s Right! It is a visual element that allows you to define a query to fetch data from entities with sources, filters, and sorting.'
    },
    {
      id: 59,
      question: 'Consider an Aggregate with a "With or Without" join between two entities. What is the expected output of the Aggregate?',
      options: [
        'All records from both Entities (FULL OUTER JOIN).',
        'Only records where there is a match between the two Entities (INNER JOIN).',
        'All records from the left entity even if there is no match in the right entity (LEFT JOIN).',
        'All records from the right entity even if there is no match in the left entity (RIGHT JOIN).'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! Yes! The With Or Without Join is equivalent to a LEFT JOIN, so the order of the Entities in the join matter!'
    },
    {
      id: 60,
      question: 'Considering that Aggregates can have hidden columns, which of the following options is correct?',
      options: [
        'Hiding columns in the Aggregate only affects the preview of the output.',
        'Columns that are empty in the database are automatically hidden.',
        'The hidden columns help optimizing the Aggregate.',
        'The hidden columns are not part of the output.'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! Correct! The hidden columns will still be available in the output.'
    },
    {
      id: 61,
      question: 'Which of the following elements can\'t be used to create calculated attributes in an Aggregate?',
      options: [
        'Value of the attributes of the Source Entities.',
        'Built-in Functions that can be translated to SQL (e.g. Length(), Power()).',
        'Variables.',
        'Server Actions using Entity Attributes.'
      ],
      correctOption: 3,
      anwserExplanation: 'That\'s Right! We can\'t do that! Would it be possible to translate all Server Actions into SQL?'
    },
    {
      id: 62,
      question: 'Consider that we want to apply aggregation functions in an Aggregate. Which of the following options is false?',
      options: [
        'We can apply multiple aggregation functions inside an Aggregate.',
        'The output of the Aggregate will contain all attributes from the Source Entities plus the aggregation columns.',
        'We can apply the following functions on attributes of integer data type: sum, max, min, count and average.',
        'The output of the Aggregate will not include the columns at grey.'
      ],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! Yes, this is false. Only the aggregation columns are returned.'
    },
    {
      id: 63,
      question: 'Considering Users and Roles in OutSystems, which of the following options is correct?',
      options: [
        'By default, end-users are managed in the built-in Users application.',
        'End-users can only be created programmatically, using Actions from the Users application.',
        'There are three built-in roles in OutSystems: Anonymous, AppUser and Registered.',
        'All users, with or without a login, have automatically the Registered Role.'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! The Users app can be accessed using the browser, where users can be created and managed.'
    },
    {
      id: 64,
      question: 'In OutSystems, how do we restrict access to a Screen?',
      options: [
        'Go to the Users application and associate the Screen to a specific role.',
        'In the Screen Properties, untick roles to restrict their access.',
        'Use the CheckRole Action.',
        'We don\'t. Only users with a username and password can access.'
      ],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! Correct! There\'s a checkbox for every Role in the app.'
    },
    {
      id: 65,
      question: 'Considering the built-in Role Actions, which of the following options is false?',
      options: [
        'The CheckRole Action checks if a user has that particular Role.',
        'The GrantRole Action allows to grant a Role to a user programmatically.',
        'The RevokeRole Action allows to remove a Role from a user programmatically.',
        'The CreateUserWithRole Action creates an end-user and assigns it the Role.'
      ],
      correctOption: 3,
      anwserExplanation: 'That\'s Right! This Action does not exist. This is actually a two step operation: create the user, and assign a role to the user.'
    },
    {
      id: 66,
      question: 'In OutSystems, where can we place breakpoints?',
      options: [
        'In Actions only (Client-side and Server-Side)',
        'Server-side logic only',
        'Client-side logic only',
        'In Actions and Variables'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! Correct! Breakpoints can only be placed in action flows, regardless of whether they are client or server-side.'
    },
    {
      id: 67,
      question: 'In OutSystems, it is possible to inspect the values of variables while debugging.',
      options: [
        'True',
        'False'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! It\'s possible to inspect the values of variables when debugging the code, depending on their scope.'
    },
    {
      id: 68,
      question: 'Which of the following commands is not available in the OutSystems debugger?',
      options: [
        'Stop Debugging',
        'Continue Request',
        'Step Over',
        'Restart Debugging'
      ],
      correctOption: 3,
      anwserExplanation: 'That\'s Right! You can\'t restart debug while its instance is being executed. You can, however, stop and start it again.'
    },
    {
      id: 69,
      question: 'When debugging a consumer module, how do we guarantee that the execution stops on breakpoints defined in the producer module?',
      options: [
        'We just need to set breakpoints in the producer module. The execution will stop on its breakpoints automatically.',
        'We need to also start the debugger on the producer module.',
        'Nothing, just leave Service Studio open.',
        'In the producer, set the Entry Module property to the consumer module.'
      ],  
      correctOption: 3,
      anwserExplanation: 'That\'s Right! After this step, we can inspect the logic of any action.'
    },
    {
      id: 70,
      question: 'On Pagination and Sorting, what do we need to set up in the aggregate to make the sort function?',
      options: [
        'Nothing will be set up automatically',
        'Add dynamic sort',
        'Add Sort Client Action',
        'Create a local variable to hold the current sort attribute'
      ],
      correctOption: 1,
      anwserExplanation: 'That’s Right! It is necessary to add dynamic sort to the aggregate.'
    },
    {
      id: 71,
      question: 'Which of the following options is correct, when implementing pagination with Tables or Lists?',
      options: [
        'The Start Index property of the Pagination holds the current page number.',
        'The Max Records property of the Pagination holds the number of records to show per page.',
        'The Total Count input of the Pagination pattern should be set to the number of records per page.'
      ],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! Whereas the Start Index is the offset.'
    },
    {
      id: 72,
      question: 'Regarding sorting in a Table, which of the following options is correct?',
      options: [
        'All header cells need to have the Sort Attribute property defined.',
        'Only the Sort Attribute of the header cells needs to be defined. Data is refreshed automatically.',
        'The On Sort event has an input parameter containing the clicked column.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! And that input is associated with the column that the end-user selected to sort by.'
    },
    {
      id: 73,
      question: 'Regarding sorting Lists, which of the following options is correct?',
      options: [
        'Lists have a built-in On Sort event.',
        'Sort clauses cannot be changed dynamically at runtime when using Lists.',
        'Other Widgets should be used to allow the end-user to define the sort criteria.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! Those Widgets would trigger a refresh of the data with the new sort criteria.'
    },
    {
      id: 74,
      question: 'In OutSystems, a Block is a reusable UI component. Which of the following is NOT correct?',
      options: [
        'A Block promotes reusability, i.e. develop once, reuse many times.',
        'A Block encapsulates its own logic.',
        'A Block improves maintainability, i.e., change the design or functionality, affect all usages.',
        'A Block can only be reused once.'
      ],
      correctOption: 3,
      anwserExplanation: 'That\'s Right! If it\'s used once, maybe it doesn\'t need to be a Block.'
    },
    {
      id: 75,
      question: 'A Block can be used...',
      options: [
        'Only inside other Screens.',
        'Inside Screens and Blocks, including itself.',
        'Inside Screens and Blocks, except on itself.',
        'Only inside other Blocks.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! Although Blocks can be used inside other Blocks, they cannot be used inside themselves as recursion is not allowed.'
    },
    {
      id: 76,
      question: 'Regarding Placeholders, which of the following options is correct?',
      options: [
        'A Placeholder reserves space in the interface to be allocated when the block is instantiated.',
        'When a Block with Placeholders is instantiated, it is mandatory to place at least one widget inside the placeholders.',
        'Placeholders can be added to Screens and Blocks.',
        'Only one placeholder may be added per Block.'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! And the content inside the Placeholder may be different for each instance.'
    },
    {
      id: 77,
      question: 'Which is the life cycle for Events?',
      options: [
        'Parameter change, Render Block, Render Screen, After Fetch.',
        'Render Screen, Render Block, Parameter Change, Render Block.',
        'On Init, Render page, render block, parameter change.'
      ],
      correctOption: 0,
      anwserExplanation: 'That’s Right! Parameter change, Render Block, Render Screen, After Fetch.'
    },
    {
      id: 78,
      question: 'Regarding Block Events, which of the following options is false?',
      options: [
        'Events can be defined at the Block or Screen level.',
        'Events allow to pass information from the Block\'s scope to the parent scope.',
        'Events are triggered by a Block and handled by its parent.',
        'Two instances of a Block may use the same handler for the same event.'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! Events allow to communicate with the parent element. Screens do not have a parent.'
    },
    {
      id: 79,
      question: 'In which of the following situations is it necessary to define a handler for a Block Event?',
      options: [
        'When the event has Input Parameters.',
        'When the Block has Placeholders.',
        'When the event Input Parameters are all mandatory.',
        'When the Event is set to mandatory.'
      ],
      correctOption: 3,
      anwserExplanation: 'That\'s Right! In these cases, a Client Action must be specified to handle the event. Although it may be empty.'
    },
    {
      id: 80,
      question: 'In which of the following situations is the On Parameters Changed Event triggered?',
      options: [
        'If the value of a Block Input Parameters changes inside a Client Action of the Block.',
        'The On Parameters Changed must be explicitly triggered by the parent of the Block.',
        'When the parent of the Block changes the value of at least one of the Block Input Parameters.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! This allows a Block to react to changes from the outside.'
    },
    {
      id: 81,
      question: 'Which of the following events is not available in Screens or Blocks?',
      options: [
        'Initialize',
        'Ready',
        'After Fetch',
        'Render'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! This event is only available in Screen Aggregates and Data Actions. It acts upon data fetched from the database or server.'
    },
    {
      id: 82,
      question: 'Considering the Initialize event of a Screen, which of the following would be the best use case for that event?',
      options: [
        'Retrieve data from the server database.',
        'Act on data returned by a Data Action.',
        'Manipulate the DOM.',
        'Set the default value of a Local Variable.'
      ],
      correctOption: 3,
      anwserExplanation: 'That\'s Right! This is the perfect place for that!'
    },
    {
      id: 83,
      question: 'Which of the following is the correct order of occurrence of events in a Screen?',
      options: [
        'Initialize, Ready, Render, Destroy.',
        'Initialize, Destroy, Ready, Render.',
        'Ready, Initialize, Render, Destroy.',
        'Initialize, Render, Ready, Destroy.'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! Remember that After Fetch only occurs for Screen Aggregates and Data Actions.'
    },
    {
      id: 84,
      question: 'Which of the following options is false regarding Screen Aggregates?',
      options: [
        'The Render Event on the Screen is triggered when an Aggregate with the Fetch property set to "only on demand" finishes its execution.',
        'A Screen Aggregate can be triggered when a screen is initializing or only On Demand.',
        'All Aggregates, by default, have the Fetch property set to On Demand.',
        'The On After Fetch Event is triggered for every Aggregate, regardless of its Fetch property.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! You\'re right; it\'s false! When an Aggregate is created, by default it will be triggered At Start.'
    },
    {
      id: 85,
      question: 'Consider an Aggregate with the Fetch property set to Only On Demand. When does that Aggregate run?',
      options: [
        'Automatically, when the Screen is initializing.',
        'Programmatically, using a Refresh Data node in a Screen Action.',
        'Automatically, when the Aggregates set to run "At Start" finish.',
        'Programmatically, using a Server Action.'
      ],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! That\'s correct. And we can use the Refresh Data node for Aggregates set to fetch data at start as well.'
    },
    {
      id: 86,
      question: 'What is a client variable?',
      options: [
        'A stored variable in the database.',
        'Is a configuration variable that allows to store long-lived and user-specific information.',
        'Is a variable that is used in screens.'
      ],
      correctOption: 1,
      anwserExplanation: 'That’s Right! Is a variable that is stored in the client browser.'
    },
    {
      id: 87,
      question: 'Which of the following options is correct regarding Client Variables?',
      options: [
        'The value of a Client Variable is shared among all logged-in users.',
        'Lists or Binary Data can also be stored on Client Variables.',
        'Client Variables should be used to store confidential information.',
        'Client Variables are useful to cache frequently accessed information.'
      ],
      correctOption: 3,
      anwserExplanation: 'That\'s Right! By caching frequently accessed values on Client Variables, it is possible to avoid requests to the server or database.'
    },
    {
      id: 88,
      question: 'Which of the following would be a good use case for a Client Variable?',
      options: [
        'Credit Card Number',
        'Profile Picture',
        'User Identifier',
        'User Name'
      ],
      correctOption: 3,
      anwserExplanation: 'That\'s Right! Since the name of the logged-in user is shown frequently, this is a good candidate for a Client Variable.'
    },
    {
      id: 89,
      question: 'In Client Variables can we store a list of Entities?',
      options: [
        'True',
        'False'
      ],
      correctOption: 1,
      anwserExplanation: 'That’s right! The client variables are limited to basic data type and Entity identifiers.'
    },
    {
      id: 90,
      question: 'A client variable is defined when the user login into the application, when is restored as default?',
      options: [
        'On destroying event.',
        'On changing the screen.',
        'On logout.',
        'Defined on Client Action.'
      ],
      correctOption: 2,
      anwserExplanation: 'That’s right! The variable resets to defaults on logout.'
    },
    {
      id: 91,
      question: 'The value of a ______ can be modified in Service Center to change the application behavior at runtime.',
      options: [
        'Site Property',
        'Client Variable',
        'Screen variable',
        'Data Entity'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! The Site property Default Value can be set at design time and modified in Service Center to be applied to the environment.'
    },
    {
      id: 92,
      question: 'Which of the following is a good use case for a Site Property?',
      options: [
        'Current user ID',
        'Total Stock Quantity of Products',
        'REST Web Service API Key',
        'Search Keyword'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! This would be a good use case!'
    },
    {
      id: 93,
      question: 'Which of the following is the correct syntax for Entities and Attributes?',
      options: [
        '{Entity}.[Attribute]',
        '(Entity).{Attribute}',
        '[Entity].{Attribute}',
        'Entity.Attribute'
      ],
      correctOption: 0,
      anwserExplanation: 'That\'s Right! Entities with curly brackets and Attributes with square brackets.'
    },
    {
      id: 94,
      question: 'Considering Aggregates and the SQL Tool, which of the following is the correct option?',
      options: [
        'All queries that can be written in an SQL Tool can be defined in an Aggregate.',
        'Joins between entities can only be defined in Aggregates.',
        'The SQL Tool allows to write queries that contain sub-queries.',
        'Attribute grouping can only be done with the SQL Tool.'
      ],
      correctOption: 2,
      anwserExplanation: 'That\'s Right! That, and much more!'
    },
    {
      id: 95,
      question: 'A developer should favor using a Structure instead of the Entity in the output of a SELECT SQL Query. Do you agree with this statement?',
      options: [
        'Yes, because queries become easier to maintain.',
        'Yes, because queries will retrieve fewer Attributes and less data.',
        'No, since it is exactly the same.',
        'No, it is preferable to use the Entity instead of the Structure.'
      ],
      correctOption: 1,
      anwserExplanation: 'That\'s Right! By selecting only and exactly the attributes you need, you\'ll ensure that the output of the query is optimized.'
    },
    {
      id: 96,
      question: 'Regarding non-SELECT queries, which of the following options is correct?',
      options: [
        'It is not possible to execute DELETE queries with the SQL Tool.',
        'It is not possible to use Query Parameters in Non-SELECT queries.',
        'It is mandatory to specify all Attributes in an INSERT query.',
        'It is mandatory to set the Output Entity or Structure.'
      ],
      correctOption: 3,
      anwserExplanation: 'That\'s Right! And usually you set it to the entity being manipulated.'
    },
    {
      id: 97,
      question: 'Is the visual environment for the developer to create applications?',
      options: [
        'Service Center',
        'Service Studio',
        'Service Manager',
        'Lifetime'
      ],
      correctOption: 1,
      anwserExplanation: 'That’s Right! The Service Studio is the environment for developing applications.'
    },
    {
      id: 98,
      question: 'Is another development environment allow you to create extensions to the platform?',
      options: [
        'Service Center',
        'Service Studio',
        'Integration Studio',
        'Lifetime'
      ],
      correctOption: 2,
      anwserExplanation: 'That’s right! The Integration Studio makes the integration with external systems like .NET code and Databases.'
    },
    {
      id: 99,
      question: 'It’s a platform for managing the server and providing an administration console, this web platform allows you to configure the platform server, monitoring the environment and inspect logs',
      options: [
        'Service Center',
        'Service Studio',
        'Integration Studio',
        'Lifetime'
      ],
      correctOption: 0,
      anwserExplanation: 'That’s Right! The Service Center will let you manage the server.'
    },
    {
      id: 100,
      question: 'Which option will allow you to track the deployments of each environment and infrastructure?',
      options: [
        'Service Center',
        'Service Studio',
        'Integration Studio',
        'Lifetime'
      ],
      correctOption: 3,
      anwserExplanation: 'That’s Right! The Lifetime will track the deployments of each environment.'
    }

  ]

  constructor() { }

  getQuestions(): IQuestion[] {
    return this.questions;
  }

  getRandomQuestions(count: number): IQuestion[] {
    return this.questions.sort(() => 0.5 - Math.random()).slice(0, count);
  }
}
